---
- name: 'Install required packages'
  apt: name="{{ item }}" state=present update_cache=yes cache_valid_time=3600
  with_items: ansible_required_packages

- name: 'Run pip install'
  pip: name="{{ item }}"
  with_items: ansible_pip_install

- name: '/etc/ansible exists'
  file: path=/etc/ansible state=directory owner=root group=root mode=0644

- name: 'Clone git repository'
  register: ansible_repo
  git:
    accept_hostkey: "yes"
    force: "yes"
    repo: "{{ ansible_repo_url }}"
    dest: "{{ ansible_install_dir }}"
    version: "{{ ansible_git_version }}"
    update: "no"

- name: 'Install ansible'
  command: chdir={{ ansible_install_dir }} make install
  when: (ansible_repo.changed is defined and ansible_repo.changed)
