---
- name: 'Install git'
  apt:
    name: 'git'
    state: 'latest'

- name: 'Install ansible with pip'
  pip:
    name: 'git+{{ ansible_repo_url }}@{{ ansible_git_version }}#egg=ansible'
    state: latest
