---
- name: 'Install required packages'
  apt: name="{{ item }}" state=present update_cache=yes cache_valid_time=86400
  with_items: ansible_required_packages

- name: 'Run pip install'
  pip: name="{{ item }}"
  with_items: ansible_pip_install

- name: '/etc/ansible exists'
  file:
    path: "/etc/ansible"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0644"

- name: 'Clone git repository'
  register: ansible_repo
  git:
    accept_hostkey: "yes"
    force: "yes"
    repo: "{{ ansible_repo_url }}"
    dest: "{{ ansible_install_dir }}"
    version: "{{ ansible_git_version }}"
    update: "no"

- name: 'Get version from VERSION file'
  shell: cat VERSION | cut -f1 -d' '
  args:
    chdir: "{{ ansible_install_dir }}"
  register: ansible_git_version
  ignore_errors: true
  changed_when: false

- name: 'Get ansible version'
  shell: ansible --version| cut -d ' ' -f2
  register: ansible_shell_version
  ignore_errors: true
  changed_when: false

- name: 'Install ansible'
  command:
    cmd: make install
    chdir: "{{ ansible_install_dir }}"
  when: (ansible_git_version.stdout_lines is not defined or
         ansible_shell_version.stdout_lines is not defined or
         ansible_git_version.stdout_lines != ansible_shell_version.stdout_lines)
