---
- name: Download ansible
  get_url:
    url: "{{ ansible_download_url }}"
    dest: "{{ ansible_download_dir }}/{{ ansible_download_url | basename }}"

- name: 'Extract archive'
  register: ansible_archive
  unarchive:
    src: "{{ ansible_download_dir }}/{{ ansible_download_url | basename }}"
    dest: "{{ ansible_download_dir }}"
    copy: "no"
    creates: "{{ ansible_download_dir }}/{{ ansible_download_archive_folder }}"

- name: 'Get version from VERSION file'
  shell: cat VERSION | cut -f1 -d' '
  args:
    chdir: "{{ ansible_download_dir }}/{{ ansible_download_archive_folder }}"
  register: ansible_install_version
  #ignore_errors: true
  changed_when: false

- name: 'Install ansible'
  command: make install
  args:
    chdir: "{{ ansible_install_dir }}"
  when: (ansible_install_version.stdout_lines is not defined or
         ansible_current_version.stdout_lines is not defined or
         ansible_install_version.stdout_lines != ansible_current_version.stdout_lines)
